// <auto-generated />
using System;
using LibroFiscal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibroFiscal.Persistence.Migrations
{
    [DbContext(typeof(LibroFiscalDbContext))]
    [Migration("20260614141623_AddIdentityModule")]
    partial class AddIdentityModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibroFiscal.Domain.Companies.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Ambiente")
                        .HasColumnType("integer")
                        .HasColumnName("AmbienteId");

                    b.Property<string>("CodigoActividad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("LibroFiscal.Domain.Companies.Entities.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PuntoVenta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Establishments", (string)null);
                });

            modelBuilder.Entity("LibroFiscal.Domain.DTE.Entities.DteDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Ambiente")
                        .HasColumnType("integer")
                        .HasColumnName("AmbienteId");

                    b.Property<string>("CodigoGeneracion")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("EstadoId");

                    b.Property<DateTimeOffset?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FechaTransmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaElectronica")
                        .HasColumnType("text");

                    b.Property<int>("IntentosTransmision")
                        .HasColumnType("integer");

                    b.Property<string>("JsonFirmado")
                        .HasColumnType("text");

                    b.Property<string>("JsonOriginal")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ModeloFacturacion")
                        .HasColumnType("integer")
                        .HasColumnName("ModeloFacturacionId");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<string>("SelloRecepcion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("TipoDte")
                        .HasColumnType("integer")
                        .HasColumnName("TipoDteId");

                    b.Property<int>("TipoTransmision")
                        .HasColumnType("integer")
                        .HasColumnName("TipoTransmisionId");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CodigoGeneracion")
                        .IsUnique()
                        .HasFilter("\"CodigoGeneracion\" IS NOT NULL");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "Estado");

                    b.ToTable("Dtes", (string)null);
                });

            modelBuilder.Entity("LibroFiscal.Domain.FiscalBooks.Entities.LibroIva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("EstadoId");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoLibro")
                        .HasColumnType("integer")
                        .HasColumnName("TipoLibroId");

                    b.Property<decimal>("TotalExento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGeneral")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGravado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNoSujeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_LibrosIva_CompanyId");

                    b.ToTable("LibrosIva", (string)null);
                });

            modelBuilder.Entity("LibroFiscal.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("RoleId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            PasswordHash = "NtVzQj7YD3Kouyuh4SCM+g==:0+0tEzq+CqbcJfG8K774w0zA3UAK6liYeC3eAnZezfo=",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("LibroFiscal.Domain.Companies.Entities.Company", b =>
                {
                    b.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.Nit", "Nit", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("Nit");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.Nrc", "Nrc", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Nrc");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.DireccionFiscal", "DireccionFiscal", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("DireccionComplemento");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Departamento");

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Municipio");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("DireccionFiscal")
                        .IsRequired();

                    b.Navigation("Nit")
                        .IsRequired();

                    b.Navigation("Nrc")
                        .IsRequired();
                });

            modelBuilder.Entity("LibroFiscal.Domain.Companies.Entities.Establishment", b =>
                {
                    b.HasOne("LibroFiscal.Domain.Companies.Entities.Company", null)
                        .WithMany("Establishments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.DireccionFiscal", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("EstablishmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("DireccionComplemento");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Departamento");

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Municipio");

                            b1.HasKey("EstablishmentId");

                            b1.ToTable("Establishments");

                            b1.WithOwner()
                                .HasForeignKey("EstablishmentId");
                        });

                    b.Navigation("Direccion")
                        .IsRequired();
                });

            modelBuilder.Entity("LibroFiscal.Domain.DTE.Entities.DteDocument", b =>
                {
                    b.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.NumeroControl", "NumeroControl", b1 =>
                        {
                            b1.Property<Guid>("DteDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(31)
                                .HasColumnType("character varying(31)")
                                .HasColumnName("NumeroControl");

                            b1.HasKey("DteDocumentId");

                            b1.ToTable("Dtes");

                            b1.WithOwner()
                                .HasForeignKey("DteDocumentId");
                        });

                    b.OwnsOne("LibroFiscal.Domain.DTE.Entities.DteEmisor", "Emisor", b1 =>
                        {
                            b1.Property<Guid>("DteDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CodigoActividad")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CodigoEstablecimiento")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Correo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DescripcionActividad")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nit")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NombreComercial")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Nrc")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PuntoVenta")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DteDocumentId");

                            b1.ToTable("Dtes");

                            b1.ToJson("Emisor");

                            b1.WithOwner()
                                .HasForeignKey("DteDocumentId");

                            b1.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.DireccionFiscal", "Direccion", b2 =>
                                {
                                    b2.Property<Guid>("DteEmisorDteDocumentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Complemento")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Departamento")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Municipio")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DteEmisorDteDocumentId");

                                    b2.ToTable("Dtes");

                                    b2.WithOwner()
                                        .HasForeignKey("DteEmisorDteDocumentId");
                                });

                            b1.Navigation("Direccion")
                                .IsRequired();
                        });

                    b.OwnsMany("LibroFiscal.Domain.DTE.Entities.DteLineItem", "CuerpoDocumento", b1 =>
                        {
                            b1.Property<Guid>("DteDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric");

                            b1.Property<string>("CodigoProducto")
                                .HasColumnType("text");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Descuento")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("IvaItem")
                                .HasColumnType("numeric");

                            b1.Property<int>("NumeroLinea")
                                .HasColumnType("integer");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("SubTotal")
                                .HasColumnType("numeric");

                            b1.Property<int>("TipoImpuesto")
                                .HasColumnType("integer");

                            b1.Property<string>("UnidadMedida")
                                .HasColumnType("text");

                            b1.HasKey("DteDocumentId", "Id");

                            b1.ToTable("Dtes");

                            b1.ToJson("CuerpoDocumento");

                            b1.WithOwner()
                                .HasForeignKey("DteDocumentId");
                        });

                    b.OwnsOne("LibroFiscal.Domain.DTE.Entities.DteReceptor", "Receptor", b1 =>
                        {
                            b1.Property<Guid>("DteDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CodigoActividad")
                                .HasColumnType("text");

                            b1.Property<string>("Correo")
                                .HasColumnType("text");

                            b1.Property<string>("Nit")
                                .HasColumnType("text");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("NombreComercial")
                                .HasColumnType("text");

                            b1.Property<string>("Nrc")
                                .HasColumnType("text");

                            b1.Property<string>("NumeroDocumento")
                                .HasColumnType("text");

                            b1.Property<string>("Telefono")
                                .HasColumnType("text");

                            b1.Property<string>("TipoDocumento")
                                .HasColumnType("text");

                            b1.HasKey("DteDocumentId");

                            b1.ToTable("Dtes");

                            b1.ToJson("Receptor");

                            b1.WithOwner()
                                .HasForeignKey("DteDocumentId");

                            b1.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.DireccionFiscal", "Direccion", b2 =>
                                {
                                    b2.Property<Guid>("DteReceptorDteDocumentId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Complemento")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Departamento")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Municipio")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DteReceptorDteDocumentId");

                                    b2.ToTable("Dtes");

                                    b2.WithOwner()
                                        .HasForeignKey("DteReceptorDteDocumentId");
                                });

                            b1.Navigation("Direccion");
                        });

                    b.OwnsOne("LibroFiscal.Domain.DTE.Entities.DteResumen", "Resumen", b1 =>
                        {
                            b1.Property<Guid>("DteDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CondicionOperacion")
                                .HasColumnType("integer");

                            b1.Property<decimal>("MontoTotalOperacion")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("SubTotal")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalDescuento")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalExenta")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalGravada")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalIva")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalNoSujeta")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("TotalPagar")
                                .HasColumnType("numeric");

                            b1.HasKey("DteDocumentId");

                            b1.ToTable("Dtes");

                            b1.ToJson("Resumen");

                            b1.WithOwner()
                                .HasForeignKey("DteDocumentId");
                        });

                    b.OwnsMany("LibroFiscal.Domain.DTE.Entities.DteStatusChange", "HistorialEstados", b1 =>
                        {
                            b1.Property<Guid>("DteDocumentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Estado")
                                .HasColumnType("integer");

                            b1.HasKey("DteDocumentId", "Id");

                            b1.ToTable("Dtes");

                            b1.ToJson("HistorialEstados");

                            b1.WithOwner()
                                .HasForeignKey("DteDocumentId");
                        });

                    b.Navigation("CuerpoDocumento");

                    b.Navigation("Emisor")
                        .IsRequired();

                    b.Navigation("HistorialEstados");

                    b.Navigation("NumeroControl")
                        .IsRequired();

                    b.Navigation("Receptor");

                    b.Navigation("Resumen")
                        .IsRequired();
                });

            modelBuilder.Entity("LibroFiscal.Domain.FiscalBooks.Entities.LibroIva", b =>
                {
                    b.OwnsOne("LibroFiscal.Domain.Common.ValueObjects.FiscalPeriod", "Periodo", b1 =>
                        {
                            b1.Property<Guid>("LibroIvaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("FiscalMonth");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("FiscalYear");

                            b1.HasKey("LibroIvaId");

                            b1.ToTable("LibrosIva");

                            b1.WithOwner()
                                .HasForeignKey("LibroIvaId");
                        });

                    b.OwnsMany("LibroFiscal.Domain.FiscalBooks.Entities.EntradaLibro", "Entradas", b1 =>
                        {
                            b1.Property<Guid>("LibroIvaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("DteId")
                                .HasColumnType("uuid");

                            b1.HasKey("LibroIvaId", "Id");

                            b1.ToTable("LibrosIva");

                            b1.ToJson("Entradas");

                            b1.WithOwner()
                                .HasForeignKey("LibroIvaId");
                        });

                    b.Navigation("Entradas");

                    b.Navigation("Periodo")
                        .IsRequired();
                });

            modelBuilder.Entity("LibroFiscal.Domain.Companies.Entities.Company", b =>
                {
                    b.Navigation("Establishments");
                });
#pragma warning restore 612, 618
        }
    }
}
